import { useMemo, useState } from "react";
import { Activity, Moon, Sun, Target } from "lucide-react";

const stars = ['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati']
const rasis=['Mesha','Rishabha','Mithuna','Kataka','Simha','Kanni','Thula','Vrischika','Dhanusu','Makara','Kumbha','Meena']
const rasiFacts={Mesha:['Aries','Mars','Initiative, courage, and beginning new efforts.'],Rishabha:['Taurus','Venus','Steadiness, care for resources, and appreciation of beauty.'],Mithuna:['Gemini','Mercury','Curiosity, communication, and learning through exchange.'],Kataka:['Cancer','Moon','Care, belonging, and attention to home and community.'],Simha:['Leo','Sun','Creative expression, generosity, and responsibility in visibility.'],Kanni:['Virgo','Mercury','Attention to detail, service, and practical refinement.'],Thula:['Libra','Venus','Balance, dialogue, and awareness of relationships.'],Vrischika:['Scorpio','Mars','Depth, persistence, and transformation.'],Dhanusu:['Sagittarius','Jupiter','Learning, exploration, and meaning-making.'],Makara:['Capricorn','Saturn','Patience, structure, and steady effort.'],Kumbha:['Aquarius','Saturn','Community, systems thinking, and independent ideas.'],Meena:['Pisces','Jupiter','Imagination, compassion, and reflective insight.']}
const starFacts={Ashwini:['Ketu','Horse head','Initiative, swift response, and renewal.'],Bharani:['Venus','Yoni / vessel','Endurance, responsibility, and transformation.'],Krittika:['Sun','Flame / blade','Discernment, refinement, and focused energy.'],Rohini:['Moon','Chariot / growth','Nourishment, creativity, and cultivation.'],Mrigashira:['Mars','Deer head','Curiosity, exploration, and seeking.'],Ardra:['Rahu','Teardrop','Change, inquiry, and emotional intensity.'],Punarvasu:['Jupiter','Quiver','Renewal, return, and resourcefulness.'],Pushya:['Saturn','Nourishing flower','Care, support, and steady learning.'],Ashlesha:['Mercury','Coiled serpent','Perception, strategy, and close observation.'],Magha:['Ketu','Royal throne','Ancestry, stewardship, and respect for lineage.'], 'Purva Phalguni':['Venus','Hammock / front legs of a bed','Creativity, ease, and connection.'],'Uttara Phalguni':['Sun','Bed / back legs of a bed','Commitment, generosity, and dependable support.'],Hasta:['Moon','Open hand','Skill, dexterity, and making things tangible.'],Chitra:['Mars','Bright jewel','Design, distinction, and imaginative craft.'],Swati:['Rahu','Young shoot / wind','Adaptability, independence, and movement.'],Vishakha:['Jupiter','Triumphal arch','Purpose, ambition, and sustained effort.'],Anuradha:['Saturn','Lotus','Friendship, cooperation, and devotion.'],Jyeshtha:['Mercury','Earring / umbrella','Protection, responsibility, and seniority.'],Mula:['Ketu','Roots','Research, foundations, and uncovering causes.'],'Purva Ashadha':['Venus','Fan / winnowing basket','Conviction, renewal, and resilience.'],'Uttara Ashadha':['Sun','Elephant tusk','Perseverance, principle, and lasting effort.'],Shravana:['Moon','Ear','Listening, study, and transmission of knowledge.'],Dhanishta:['Mars','Drum','Rhythm, collective work, and resourcefulness.'],Shatabhisha:['Rahu','Empty circle','Inquiry, privacy, and restoration.'],'Purva Bhadrapada':['Jupiter','Front legs of a cot','Intensity, ideals, and reflection.'],'Uttara Bhadrapada':['Saturn','Back legs of a cot','Depth, patience, and steadiness.'],Revati:['Mercury','Fish / drum','Guidance, protection, and completion.']}
const cities = { Chennai:{lat:13.0827,lon:80.2707,tz:5.5}, Bengaluru:{lat:12.9716,lon:77.5946,tz:5.5}, Mumbai:{lat:19.076,lon:72.8777,tz:5.5}, Delhi:{lat:28.6139,lon:77.209,tz:5.5}, Coimbatore:{lat:11.0168,lon:76.9558,tz:5.5}, Madurai:{lat:9.9252,lon:78.1198,tz:5.5}, Singapore:{lat:1.3521,lon:103.8198,tz:8}, London:{lat:51.5072,lon:-0.1276,tz:0}, 'New York':{lat:40.7128,lon:-74.006,tz:-4} }
const todayISO=()=>new Date().toLocaleDateString('en-CA')
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const slots={rahu:{Sunday:7,Monday:1,Tuesday:6,Wednesday:4,Thursday:5,Friday:3,Saturday:2},yama:{Sunday:4,Monday:3,Tuesday:2,Wednesday:1,Thursday:0,Friday:6,Saturday:5},gulikai:{Sunday:6,Monday:5,Tuesday:4,Wednesday:3,Thursday:2,Friday:1,Saturday:0}}
const taraNames=['Janma','Sampat','Vipat','Kshema','Pratyari','Sadhaka','Naidhana','Mitra','Parama Mitra']
const taraGuidance={Janma:{try:'Keep the day steady: attend to familiar routines and personal reflection.',avoid:'If your custom observes Janma Tara, defer major auspicious beginnings.'},Sampat:{try:'Traditionally associated with resources; organize finances or plan practical next steps.',avoid:'Avoid treating this as a promise of financial gain.'},Vipat:{try:'Keep plans simple, check details, and leave extra time for transitions.',avoid:'Some traditions defer major new beginnings on Vipat Tara.'},Kshema:{try:'Traditionally associated with wellbeing; focus on maintenance, rest, and supportive routines.',avoid:'Do not use the reading in place of health advice.'},Pratyari:{try:'Work through existing tasks carefully and communicate expectations clearly.',avoid:'Some traditions postpone significant beginnings on Pratyari Tara.'},Sadhaka:{try:'Choose one focused task and make steady progress toward it.',avoid:'Treat effort as useful in its own right; no outcome is guaranteed.'},Naidhana:{try:'Prefer routine, review, and low-pressure tasks.',avoid:'Many Tara Bala traditions avoid auspicious beginnings on Naidhana Tara.'},Mitra:{try:'Make time for cooperation, learning, or a thoughtful conversation.',avoid:'Keep ordinary judgment central to important decisions.'},'Parama Mitra':{try:'Traditionally associated with support; use the day for constructive collaboration.',avoid:'This is a cultural reading, not a guarantee of success.'}}
const metricInfo={sleep:{label:'Sleep',unit:'h',goal:8,icon:Moon},activity:{label:'Movement',unit:'min',goal:30,icon:Activity},study:{label:'Focused learning',unit:'min',goal:60,icon:Target},water:{label:'Water',unit:'glasses',goal:8,icon:Sun}}
const seedRows=()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return {date:d.toLocaleDateString('en-CA'),sleep:[6.5,7,6,7.5,6.5,8,7][i],activity:[20,35,15,40,25,30,45][i],study:[50,65,35,70,45,80,60][i],water:[6,7,5,8,6,7,8][i]}})
function moonStar(dateString,timeString,city){
  const [year,month,day]=dateString.split('-').map(Number),[hour,minute]=String(timeString||'12:00').split(':').map(Number)
  const utc=new Date(Date.UTC(year,month-1,day,hour,minute)-city.tz*3600000);if(Number.isNaN(+utc))return null
  const jd=utc.getTime()/86400000+2440587.5,T=(jd-2451545)/36525
  const L=(218.3164477+481267.88123421*T-0.0015786*T*T)%360,D=(297.8501921+445267.1114034*T-0.0018819*T*T)%360,M=(357.5291092+35999.0502909*T-0.0001536*T*T)%360,Mp=(134.9633964+477198.8675055*T+0.0087414*T*T)%360,F=(93.272095+483202.0175233*T-0.0036539*T*T)%360
  const rad=x=>x*Math.PI/180;let lon=L+6.289*Math.sin(rad(Mp))+1.274*Math.sin(rad(2*D-Mp))+.658*Math.sin(rad(2*D))+.214*Math.sin(rad(2*Mp))-.186*Math.sin(rad(M))-.114*Math.sin(rad(2*F));lon=((lon-24.1)%360+360)%360
  const width=360/27,ix=Math.floor(lon/width);return {name:stars[ix],pada:Math.floor((lon%width)/width*4)+1,rasi:rasis[Math.floor(lon/30)],longitude:lon}
}
function solarTimes(dateString,city){const date=new Date(`${dateString}T12:00:00Z`),n=Math.ceil((Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())-Date.UTC(date.getUTCFullYear(),0,1))/86400000),g=2*Math.PI/365*(n-1),dec=.006918-.399912*Math.cos(g)+.070257*Math.sin(g)-.006758*Math.cos(2*g)+.000907*Math.sin(2*g)-.002697*Math.cos(3*g)+.00148*Math.sin(3*g),lat=city.lat*Math.PI/180,zenith=90.833*Math.PI/180,cosH=Math.cos(zenith)/(Math.cos(lat)*Math.cos(dec))-Math.tan(lat)*Math.tan(dec);if(cosH>1||cosH< -1)return null;const H=Math.acos(cosH)*180/Math.PI,eq=229.18*(.000075+.001868*Math.cos(g)-.032077*Math.sin(g)-.014615*Math.cos(2*g)-.040849*Math.sin(2*g)),noon=720-4*city.lon-eq+city.tz*60;return {sunrise:noon-4*H,sunset:noon+4*H}}
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
function fmt(min){min=(Math.round(min)%1440+1440)%1440;return `${String(Math.floor(min/60)).padStart(2,'0')}:${String(min%60).padStart(2,'0')}`}
function intervals(date,city){const sun=solarTimes(date,city);if(!sun)return[];const weekday=dayNames[new Date(`${date}T12:00:00`).getDay()],part=(sun.sunset-sun.sunrise)/8;return Object.entries(slots).map(([id,byDay])=>({id,label:id==='rahu'?'Rahu Kalam':id==='yama'?'Yamagandam':'Gulikai Kalam',start:sun.sunrise+part*byDay[weekday],end:sun.sunrise+part*(byDay[weekday]+1)})).sort((a,b)=>a.start-b.start)}
function seasonFor(date){const m=Number(date.slice(5,7));if([4,5].includes(m))return ['Ilavenil','Early summer in the traditional Tamil seasonal cycle.'];if([6,7].includes(m))return ['Mudhuvenil','Peak summer; seasonal customs differ by region.'];if([8,9].includes(m))return ['Kaar','Monsoon season in the traditional cycle.'];if([10,11].includes(m))return ['Kuthir','Cool season; a time for seasonal routine reflection.'];if([12,1].includes(m))return ['Munpani','Dewy/cool season in the traditional cycle.'];return ['Pinpani','Late cool season moving toward warmer months.']}
function average(rows,key){return rows.length?rows.reduce((sum,r)=>sum+Number(r[key]||0),0)/rows.length:0}

export default function useAppModel() {
  const [profile, setProfile] = useState(() => readJSON('nakshatra-profile', null));
  const [date, setDate] = useState(todayISO);
  const [checkins, setCheckins] = useState(() => readJSON('nakshatra-checkins', seedRows()));
  const [feedback, setFeedbackState] = useState(() => readJSON('nakshatra-feedback', {}));
  const [form, setForm] = useState({sleep:7, movement:30, learning:45, water:7});
  const [whatIfValue, setWhatIfValue] = useState(30);
  const [whatIfMetric, setWhatIfMetric] = useState('sleep');
  const [toast, setToast] = useState('');
  const city = cities[profile?.city] || cities.Chennai;
  const birthCity = cities[profile?.birthCity] || cities.Chennai;
  const birthStar = useMemo(() => profile?.birthDate ? moonStar(profile.birthDate, profile.birthTime, birthCity) : null, [profile, birthCity]);
  const dayStar = useMemo(() => moonStar(date, '12:00', city), [date, city]);
  const tara = useMemo(() => birthStar && dayStar ? taraNames[((stars.indexOf(dayStar.name)-stars.indexOf(birthStar.name)+27)%27)%9] : null, [birthStar, dayStar]);
  const times = useMemo(() => intervals(date, city), [date, city]);
  const recent = useMemo(() => [...checkins].sort((a,b)=>a.date.localeCompare(b.date)).slice(-7), [checkins]);
  const averages = useMemo(() => Object.fromEntries(Object.keys(metricInfo).map(k => [k, average(recent,k)])), [recent]);
  const score = useMemo(() => Math.round(Object.keys(metricInfo).reduce((sum,k)=>sum+Math.min(100,averages[k]/metricInfo[k].goal*100),0)/4), [averages]);
  const season = seasonFor(date);
  const priority = (k) => averages[k]/metricInfo[k].goal + (feedback[k]==='Helpful'?.25:feedback[k]==='Later'?.1:feedback[k]==='Not helpful'?.5:0);
  const recs = useMemo(() => {
    const keys=Object.keys(metricInfo).sort((a,b)=>priority(a)-priority(b));
    const copy={sleep:['Try a consistent wind-down time tonight. Your recent sleep average is below your chosen 8-hour reference.','Avoid making a drastic schedule change; move bedtime gradually.'],activity:['Add a comfortable 10-minute walk or stretch break today.','Avoid treating a missed activity goal as failure; resume with a manageable step.'],study:['Schedule one short, distraction-light focus block.','Avoid filling every open hour; include breaks.'],water:['Keep water nearby and check in with thirst throughout the day.','Avoid forcing a fixed amount without considering your needs or medical advice.']};
    return keys.slice(0,3).map(metric=>({id:metric,metric,title:`A small ${metricInfo[metric].label.toLowerCase()} reset`,text:`${copy[metric][0]} ${tara?taraGuidance[tara].try:''}`,avoid:copy[metric][1],context:tara?`${metricInfo[metric].label} check-ins + ${tara} Tara reflection`:`Based on your recent ${metricInfo[metric].label.toLowerCase()} check-ins`}));
  }, [averages,tara,feedback]);
  const palanRaw = useMemo(() => {
    const dayName=new Date(`${date}T12:00:00`).toLocaleDateString('en-IN',{weekday:'long'});
    const theme=taraGuidance[tara||'Janma'].try;
    const focusKey=Object.keys(metricInfo).sort((a,b)=>averages[a]/metricInfo[a].goal-averages[b]/metricInfo[b].goal)[0];
    const focus=metricInfo[focusKey].label.toLowerCase();
    const dayTone={Sunday:'Set a clear intention, then leave room for rest.',Monday:'Keep plans flexible and notice what needs attention.',Tuesday:'Choose one task that benefits from direct, steady effort.',Wednesday:'Make space for useful conversations and learning.',Thursday:'Review the bigger picture before choosing your next step.',Friday:'Bring care and creativity to one task or interaction.',Saturday:'Favor patience, organization, and a measured pace.'}[dayName];
    return {dayName,theme,focus,dayTone};
  },[date,tara,averages]);
  const raasi=birthStar?.rasi || '';
  const raasiDetails=rasiFacts[raasi];
  const caution=['Vipat','Pratyari','Naidhana'].includes(tara);
  const palan={sections:[
    {title:'Financial & Business',text:caution?'Keep financial and business decisions measured; review costs, agreements, and timelines before committing.':'Use a practical approach to work and money; check details and plan before acting on an opportunity.'},
    {title:'Work & Career',text:`${palanRaw.theme} ${palanRaw.dayTone}`},
    {title:'Family & Relationships',text:`Favor patient, direct conversation and make room for others’ perspectives. ${raasiDetails?.[2]||''}`},
    {title:'Health & Routine',text:`Treat wellbeing as a routine check-in, not a prediction. Choose one manageable habit; recent tracked focus: ${palanRaw.focus}.`}
  ],avoid:caution?'Avoid rushing important commitments, unnecessary arguments, and signing or spending without checking details.':tara==='Janma'?'Avoid overloading the day or making a major choice under pressure.':'Avoid overpromising, impulsive spending, and letting minor disagreements grow.',links:[{label:`Open today’s ${raasiDetails?.[0]||'Raasi'} Palan`,url:`https://www.tamildailycalendar.com/tamil_rasi_palan_today.php?msg=Tamil%20Rasi%20Palan%20Today&rasi=${({Mesha:'MESHAM',Rishabha:'RISHABAM',Mithuna:'MITHUNAM',Kataka:'KATAKAM',Simha:'SIMMAM',Kanni:'KANNI',Thula:'THULAM',Vrischika:'VIRUCHIKAM',Dhanusu:'DANUSU',Makara:'MAKARAM',Kumbha:'KUMBAM',Meena:'MEENAM'})[raasi]||'KANNI'}`},...(raasi==='Kanni'?[{label:'Dinakaran',url:'https://astrology.dinakaran.com/today_rasipalan/today_rasipalan-virgo/'},{label:'Oneindia Tamil',url:'https://tamil.oneindia.com/astrology/kanni-rasi-palan-today.html'},{label:'Tamil Murasu',url:'https://www.tamilmurasu.com.sg/horoscope/virgo'},{label:'Vikatan (weekly)',url:'https://www.vikatan.com/horoscope/weekly-rasipalan/kanni'}]:[])]};
  const saveProfileData = (draft) => { const p={...draft,loggedIn:true}; localStorage.setItem('nakshatra-profile',JSON.stringify(p)); setProfile(p); };
  const logout = () => { localStorage.removeItem('nakshatra-profile'); setProfile(null); };
  const setFeedback = (id,value) => { const next={...feedback,[id]:value}; setFeedbackState(next); localStorage.setItem('nakshatra-feedback',JSON.stringify(next)); };
  const saveCheckin = () => {
    const row={date:todayISO(),sleep:Number(form.sleep),activity:Number(form.movement),study:Number(form.learning),water:Number(form.water)};
    const next=[...checkins.filter(r=>r.date!==row.date),row].sort((a,b)=>a.date.localeCompare(b.date));
    setCheckins(next); localStorage.setItem('nakshatra-checkins',JSON.stringify(next)); setDate(todayISO());
    setToast('Check-in saved — your Digital Twin has been updated.'); window.setTimeout(()=>setToast(''),4500);
  };
  const setFormValue = (next) => setForm(typeof next === 'function' ? next : next);
  const whatIfCurrent = Object.keys(metricInfo).reduce((sum,key)=>sum+Math.min(100,averages[key]/metricInfo[key].goal*100),0)/4;
  const whatIfDelta = whatIfMetric==='sleep' ? whatIfValue/60 : whatIfValue;
  const whatIfNextAverage = averages[whatIfMetric] + whatIfDelta;
  const whatIfProjected = (whatIfCurrent*4 - Math.min(100,averages[whatIfMetric]/metricInfo[whatIfMetric].goal*100) + Math.min(100,whatIfNextAverage/metricInfo[whatIfMetric].goal*100))/4;
  const whatIf = {metric:whatIfMetric,setMetric:(metric)=>{setWhatIfMetric(metric);setWhatIfValue(metric==='water'?1:30)},value:whatIfValue,setValue:setWhatIfValue,label:'Change to daily routine',min:whatIfMetric==='water'?1:5,max:whatIfMetric==='water'?4:60,step:whatIfMetric==='water'?1:5,unit:whatIfMetric==='sleep'?'minutes of sleep':whatIfMetric==='water'?'glasses per day':'minutes per day',current:Number(whatIfCurrent.toFixed(1)),projected:Number(whatIfProjected.toFixed(1)),atGoal:averages[whatIfMetric]>=metricInfo[whatIfMetric].goal};
  const profileView=profile ? {...profile,raasi:raasiDetails?.[0]||'Unknown',nakshatra:birthStar?.name||'Unknown'} : null;
  const twin={score,sleep:Number(averages.sleep.toFixed(1)),movement:Number(averages.activity.toFixed(1)),learning:Number(averages.study.toFixed(1)),water:Number(averages.water.toFixed(1)),summary:`A ${score}% consistency score across your latest ${recent.length} check-ins.`};
  const normalizedRows=recent.map(r=>({...r,movement:r.activity,learning:r.study}));
  const starInfo={nakshatra:birthStar?.name||'Unavailable',pada:birthStar?.pada||'—',raasi:raasiDetails?.[0]||'Unavailable',notes:birthStar?[`Traditional ruler: ${starFacts[birthStar.name]?.[0]}.`,`Traditional symbol: ${starFacts[birthStar.name]?.[1]}.`,starFacts[birthStar.name]?.[2]||'',raasiDetails?.[2]||'']:['Enter birth details to estimate your Nakshatra and Janma Raasi.']};
  const panchangam=times.map(t=>({label:t.label,start:fmt(t.start),end:fmt(t.end),note:'Traditionally avoided for starting auspicious ventures.'}));
  const iks=[{title:'Nakshatra',text:`Birth star estimate: ${birthStar?.name||'unavailable'}${birthStar?`, Pada ${birthStar.pada}.`:'.'}`},{title:'Panchanga',text:`Vara: ${new Date(`${date}T12:00:00`).toLocaleDateString('en-IN',{weekday:'long'})}; estimated midday Nakshatra: ${dayStar?.name||'unavailable'}. Tithi, Yoga and Karana are not calculated in this preview.`},{title:'Dinacharya',text:'Self-reported sleep, movement, focused learning and water entries form a simple daily rhythm view.'},{title:'Ritucharya',text:`${season[0]} — ${season[1]} Seasonal customs vary by place and tradition.`}];
  return {profile:profileView,profileDraft:profile,saveProfileData,logout,date,setDate,panchangam,palan,twin,checkins:normalizedRows,form,setForm:setFormValue,saveCheckin,recs,feedback,setFeedback,whatIf,starInfo,iks,disclaimer:'Traditional context and self-reported habit reflection; not a scientific forecast.',toast,setToast,cityName:profile?.city||'Chennai',rawFeedback:feedback,setWhatIfMetric};
}
